version: '3.1'

services:
  db:
    image: "postgres:10-alpine"
    restart: always
    ports:
      - "5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_USER: "root"
    network_mode: bridge